name: Docker CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

env:
  docker-repo: loyayz
  docker-image: docker-zhparser

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    strategy:
      matrix:
        postgres: [12, 13, 14, 15]

    name: Build docker image for ${{ matrix.postgres }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build docker image for ${{ matrix.postgres }}
        run: |
          cd ${{ matrix.postgres }}
          docker build -t ${{ env.docker-repo }}/${{ env.docker-image }}:${{ matrix.postgres }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push docker image to Docker Hub
        if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
        run: docker push ${{ env.docker-repo }}/${{ env.docker-image }}:${{ matrix.postgres }}
